# https://github.com/bridgecrewio/checkov
# https://megalinter.io/latest/descriptors/repository_checkov/
---
skip-check:
  - CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_3 # Ensure that a user for the container has been created
  - CKV_DOCKER_8 # Ensure the last USER is not root
