# https://megalinter.io/configuration/
---
VALIDATE_ALL_CODEBASE: true

DISABLE:
  - COPYPASTE
  - SPELL
DISABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - MAKEFILE_CHECKMAKE
  - PYTHON_BANDIT
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY

SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA: false
